LET RESPOSTA = RND(100)
100 INPUT "Palpite: "; PALPITE

IF PALPITE = RESPOSTA THEN GOTO 200 
IF PALPITE > RESPOSTA THEN GOTO 300
IF PALPITE < RESPOSTA THEN GOTO 400
  
  
200 PRINT "PARABÉNS, ACERTOU!!"
END
300 PRINT "A reposta é um número menor..." 
GOTO 100
400 PRINT "A reposta é um número maior..." 
GOTO 100
